/* team-facts.js — 20 facts per F1 team, updates with team selector */

(function () {
  const FACTS = {
    ferrari: [
      "Oldest team on the grid — racing since 1929.",
      "The only team to have competed in every single F1 season.",
      "16 constructors' championships — more than any other team.",
      "The Prancing Horse logo was a gift from WWI ace Francesco Baracca's mother.",
      "Rosso Corsa (racing red) was Italy's official racing colour since the 1900s.",
      "Enzo Ferrari called his cars 'weapons' and his drivers 'cannon fodder'.",
      "First F1 win: 1951 British GP with José Froilán González.",
      "Over 240 race victories — the most in F1 history.",
      "Every Ferrari road car is tested at the Fiorano circuit before delivery.",
      "Michael Schumacher won 5 consecutive titles with them (2000–2004).",
      "The Maranello factory is less than 1 hour from Bologna airport.",
      "Charles Leclerc is the first Monégasque to race for Ferrari.",
      "Their wind tunnel operates 24 hours a day, 7 days a week.",
      "Ferrari has its own museum with 35+ championship-winning race cars.",
      "Niki Lauda survived a near-fatal crash at the 1976 Nürburgring — and nearly won the title that year.",
      "Felipe Massa missed the 2008 title by a single point on the final lap of the final race.",
      "The Ferrari red is so specific it has its own registered Pantone shade.",
      "Sebastian Vettel joined Ferrari in 2015 hoping to end a decade-long title drought.",
      "Hamilton left Mercedes for Ferrari in 2025 — the biggest transfer in F1 history.",
      "In 2004, Schumacher won 13 out of 18 races. In a Ferrari.",
    ],
    mercedes: [
      "The 'Silver Arrows' name dates to 1934 — they stripped the white paint to save weight.",
      "Won 8 consecutive constructors' championships from 2014 to 2021.",
      "The team is based in Brackley, England — not Germany.",
      "Their power units are built separately in Brixworth, Northamptonshire.",
      "Returned to F1 in 2010 by buying Brawn GP, who had won the title in 2009.",
      "Lewis Hamilton's 7 world titles were all won with Mercedes power.",
      "Nico Rosberg won the 2016 title — then retired 5 days later.",
      "They won 15 of 21 races in 2016. Still the dominant season record.",
      "The 2014 hybrid power unit was so advanced rivals spent years catching up.",
      "Introduced the controversial DAS (Dual Axis Steering) system in 2020.",
      "Toto Wolff co-owns the team and has been Team Principal since 2013.",
      "Mercedes supplied engines to McLaren for 20 years before going solo.",
      "George Russell replaced Hamilton in 2022 at just 24 years old.",
      "Kimi Antonelli joined in 2025 as Hamilton's replacement at 18.",
      "The AMG suffix stands for Aufrecht, Melcher and Großaspach — the founders.",
      "Their simulator in Brackley is one of the most advanced in motorsport.",
      "In 2020 Hamilton equalled Schumacher's record of 91 race wins.",
      "The iconic silver is unpainted aluminium — a tradition from pre-war racing.",
      "They lost the 2021 title to Red Bull on the very last lap of the last race.",
      "Hamilton's final win for Mercedes came at Saudi Arabia 2021.",
    ],
    mclaren: [
      "Founded by New Zealander Bruce McLaren in 1963. He died testing a car in 1970.",
      "Based at the McLaren Technology Centre in Woking — it cost £300 million to build.",
      "The 1988 MP4/4 won 15 of 16 races — still the highest win rate in F1 history.",
      "Ayrton Senna and Alain Prost's rivalry at McLaren (1988–89) is the greatest in F1.",
      "Their papaya orange livery is a tribute to Bruce McLaren's New Zealand roots.",
      "Lando Norris scored his first win at Miami 2024 after 110 race starts.",
      "McLaren was the first team to use a full carbon fibre monocoque chassis (1981).",
      "Mika Häkkinen won back-to-back titles in 1998 and 1999.",
      "Lewis Hamilton made his F1 debut with McLaren in 2007 — almost won the title.",
      "Ron Dennis led the team for over 30 years with an obsession for perfection.",
      "McLaren also builds road hypercars, defence systems, and applied technologies.",
      "The team went through Honda, Renault, and Mercedes engines in 4 years (2015–2018).",
      "Oscar Piastri joined in 2023 after Alpine controversially tried to block his move.",
      "McLaren's Racing Academy has developed multiple future F1 drivers.",
      "Zak Brown joined as CEO in 2016 and turned the team from midfield to title contender.",
      "The MCL branding replaces the old MP — meaning McLaren Carbon Longtail.",
      "Their 2023 upgrade package at Austria was the biggest single-race gain in recent history.",
      "Norris and Piastri are the youngest McLaren pairing since Senna and Prost.",
      "McLaren holds the record for most podiums without a title: 1998–present.",
      "They supply the safety car coordination software to the FIA.",
    ],
    red_bull: [
      "Red Bull entered F1 in 2005 by buying the struggling Jaguar Racing team for $1.",
      "Sebastian Vettel won 4 consecutive world titles with them (2010–2013).",
      "Max Verstappen won 4 consecutive titles (2021–2024) — equalling Vettel.",
      "In 2023 they won 21 of 22 races — the most dominant season in F1 history.",
      "Their Milton Keynes factory, Red Bull Racing HQ, is called the 'Milton Keynes Campus'.",
      "Adrian Newey designed their championship-winning cars from 2010 to 2023.",
      "Red Bull also operates sister team Racing Bulls (formerly Toro Rosso/AlphaTauri).",
      "Verstappen became the youngest ever points scorer in F1 at just 17.",
      "The RB initials on the car stand for Red Bull, not the constructors' championship name.",
      "Their energy drink brand funds an entire junior driver programme.",
      "Dietrich Mateschitz, who founded the Red Bull empire, died in 2022.",
      "Red Bull's F1 budget is estimated at over $400 million per year.",
      "Verstappen's engineer Gianpiero Lambiase left in 2026 — a major blow.",
      "They switched from Renault to Honda power in 2019 — and immediately competed for titles.",
      "The 2022 cost cap breach fine ($7 million) changed how F1 polices spending.",
      "Christian Horner has been Team Principal since the very first Red Bull race in 2005.",
      "Verstappen lapped every other driver in the 2023 Dutch Grand Prix.",
      "Red Bull's junior programme has produced Vettel, Ricciardo, Gasly, Tsunoda, and Verstappen.",
      "Their pit crew has set multiple world records for fastest pit stops.",
      "Sergio Perez won 13 races for Red Bull before being replaced by Liam Lawson in 2025.",
    ],
    aston_martin: [
      "Aston Martin returned to F1 in 2021 after 60 years away, buying Racing Point.",
      "The team is based in Silverstone — literally inside the circuit complex.",
      "Lawrence Stroll bought Force India out of administration in 2018 for his son Lance.",
      "Fernando Alonso joined in 2023 and scored 8 podiums in his debut season.",
      "The Aston Martin name in F1 dates back to the 1950s — 60 years of absence followed.",
      "Their factory is a brand new state-of-the-art facility opened in 2023.",
      "Dan Fallows joined from Red Bull as Technical Director in 2022.",
      "The green livery — British Racing Green — is the oldest racing colour tradition.",
      "Aston Martin road cars use an AMG-sourced V8 engine.",
      "Lance Stroll is one of only a handful of drivers whose father owns the team.",
      "Their 2023 AMR23 was the most improved car on the grid at the start of the season.",
      "Alonso's podium at the 2023 Bahrain GP was his first in over 5 years.",
      "The team was known as Jordan, BAR, Honda, Brawn, Mercedes, Force India, Racing Point.",
      "Jenson Button won his 2009 title with the team when it was called Brawn GP.",
      "They are building a new wind tunnel to rival Red Bull and Mercedes.",
      "Mike Krack became Team Principal in 2022, replacing Otmar Szafnauer.",
      "Aston Martin's road car factory is in Gaydon, Warwickshire — near the F1 base.",
      "The Cognizant sponsorship was one of the largest title sponsorships in F1.",
      "Their race suits feature a subtle Aston Martin wings badge, just like the road cars.",
      "Stroll Sr invested over $400 million transforming the team's infrastructure.",
    ],
    alpine: [
      "Alpine is the French manufacturer arm of Renault, which returned to F1 under this name in 2021.",
      "Renault won back-to-back titles in 2005 and 2006 with Fernando Alonso.",
      "The team is based in Enstone, UK — not France.",
      "Their engine is built at the Viry-Châtillon facility near Paris.",
      "Pierre Gasly joined from AlphaTauri in 2023, replacing Alonso.",
      "Esteban Ocon scored Alpine's only win of the modern era at Hungary 2021.",
      "The blue livery references the French tricolore and Alpine's road car heritage.",
      "Alpine's road car, the A110, is considered one of the best driver's cars in Europe.",
      "Renault has been involved in F1 since 1977 — as engine supplier and constructor.",
      "The team has had 7 different names: Toleman, Benetton, Renault, Lotus, Renault, Alpine.",
      "Michael Schumacher won his first title with them in 1994 when they were Benetton.",
      "Briatore and Symonds were banned after the 2008 Singapore 'Crashgate' scandal.",
      "They ran the first turbocharged F1 engine — the Renault EF1 in 1977.",
      "Jack Doohan replaced Ocon for the 2025 season after a turbulent driver selection process.",
      "Bruno Famin became Team Principal in 2023 after a chaotic summer.",
      "Alpine's Academy produced Ocon, Gasly, and several Formula 2 champions.",
      "They briefly considered leaving F1 in 2024 due to cost concerns.",
      "The A523 was famously difficult to drive — described as 'undriveable' by drivers.",
      "Renault's RS engines powered Red Bull's title-winning cars from 2010 to 2013.",
      "Alpine is the only French constructor currently competing in F1.",
    ],
    williams: [
      "Williams won 7 constructors' championships — third most in F1 history.",
      "Founded by Sir Frank Williams in 1977 from almost nothing.",
      "Ayrton Senna died driving a Williams at Imola 1994 — the darkest day in F1.",
      "The team was sold to Dorilton Capital in 2020 after Sir Frank's health declined.",
      "Carlos Sainz joined for 2025 after being dropped by Ferrari.",
      "Alex Albon has been the team's cornerstone driver since 2022.",
      "Williams used to design and build everything in-house — including their own gearboxes.",
      "In 1992, Nigel Mansell won 9 of the first 10 races. In a Williams.",
      "The Grove, Oxfordshire factory is surrounded by farmland — very English.",
      "Their FW numbering system dates back to 1969 — FW stands for Frank Williams.",
      "Damon Hill won the 1996 title with Williams, son of Graham Hill who won in 1962.",
      "Williams signed Pastor Maldonado in 2012 partly due to $45 million in Venezuelan backing.",
      "Maldonado won the 2012 Spanish GP — Williams' last race victory.",
      "Sir Frank Williams ran the team from a wheelchair after a road accident in 1986.",
      "Claire Williams stepped down as Deputy Team Principal after the sale in 2020.",
      "Williams was the first team to use active suspension and semi-automatic gearbox.",
      "They've scored points with over 50 different drivers across their history.",
      "The iconic blue and white livery with the Rothmans sponsor is considered F1's most beautiful.",
      "James Vowles joined as Team Principal in 2023 from Mercedes.",
      "Williams produced the FW14B — voted the greatest F1 car of all time by many engineers.",
    ],
    racing_bulls: [
      "The team started as Minardi in 1985 — a beloved backmarker with zero wins.",
      "Red Bull bought Minardi in 2005 for $1 to create their junior team.",
      "Known as Toro Rosso ('Red Bull' in Italian) from 2006 to 2019.",
      "Sebastian Vettel won their only race — the 2008 Italian GP at Monza in the wet.",
      "Rebranded as AlphaTauri in 2020, then Racing Bulls in 2024.",
      "Based in Faenza, Italy — making them the only Italian-based team on the grid.",
      "Their sister team Red Bull has won 4 constructors' titles using alumni from this team.",
      "Verstappen, Kvyat, Gasly, Tsunoda, and Ricciardo all passed through the Red Bull system.",
      "Liam Lawson replaced Sergio Perez at Red Bull in 2025 after racing here.",
      "The team's cars are largely designed in Milton Keynes alongside Red Bull.",
      "They use Red Bull's wind tunnel and many shared technical resources.",
      "Franz Tost was Team Principal for 18 years — one of the longest tenures in F1.",
      "Laurent Mekies joined from Ferrari as Team Principal in 2024.",
      "Racing Bulls launched a new brand identity with a completely redesigned car in 2024.",
      "Their Faenza base is in the same town as the famous International Racing Car Museum.",
      "Yuki Tsunoda has been with the team since 2021 — a loyal Red Bull development success.",
      "Isack Hadjar joined for 2025 — another Red Bull junior graduating to the main team.",
      "The team has helped Red Bull identify which junior drivers are ready for the senior team.",
      "They ran Ferrari engines from 2006-2018 before switching to Honda.",
      "Minardi's last points finish was in 2005 — their proudest moment before the buyout.",
    ],
    haas: [
      "The only American-owned team currently in F1.",
      "Gene Haas also co-owns the Stewart-Haas NASCAR team.",
      "Founded in 2016 — the newest team on the grid.",
      "Based in Kannapolis, North Carolina, but their car is built in Banbury, England.",
      "They use Ferrari power units and many Ferrari-developed components.",
      "Romain Grosjean's fiery Bahrain crash in 2020 was one of F1's most dramatic.",
      "Grosjean walked away from a fireball that split his car in half — a miracle.",
      "Kevin Magnussen returned to the team in 2022 after a year away.",
      "Nikita Mazepin was dropped after Russia's invasion of Ukraine — one race into 2022.",
      "Haas has never scored a podium finish in their entire history.",
      "Their best constructors' championship result is 5th place (2018).",
      "Guenther Steiner was their famous, profanity-loving Team Principal until 2024.",
      "Steiner's candid moments made Drive to Survive arguably its funniest content.",
      "Ayao Komatsu replaced Steiner as Team Principal in 2024.",
      "Oliver Bearman made his F1 debut as Ferrari substitute at Saudi Arabia 2024 — aged 19.",
      "Bearman scored points on debut, securing a full-time seat at Haas for 2025.",
      "The team's livery has changed dramatically every season — no consistent identity.",
      "They ran the controversial 'pink Mercedes' season in 2020 wearing Racing Point colours.",
      "Haas has the smallest workforce of any team — around 250 people.",
      "Their business model relies heavily on Ferrari's supply chain to keep costs down.",
    ],
    audi: [
      "Audi joined F1 in 2026 by taking over the Sauber/Alfa Romeo team.",
      "Their entry marks the first major German manufacturer to join F1 in over a decade.",
      "Sauber has been in F1 since 1993 — one of the longest-running backmarkers.",
      "The team is based in Hinwil, Switzerland — the only Swiss-based F1 team.",
      "Sauber's wind tunnel in Hinwil is considered one of the best in the sport.",
      "Robert Kubica survived a horrific rally crash in 2011 and made an F1 comeback in 2019.",
      "The Alfa Romeo rebrand ran from 2019 to 2023 — Ferrari-powered throughout.",
      "Kimi Räikkönen ended his F1 career with Alfa Romeo in 2021 with a record 349 starts.",
      "Nico Hulkenberg joined the Audi project as their lead experienced driver.",
      "Audi has won Le Mans 13 times — one of motorsport's greatest records.",
      "The four Audi rings represent the four companies that merged to form Auto Union in 1932.",
      "Auto Union competed in Grand Prix racing in the 1930s alongside Mercedes.",
      "Audi's F1 power unit is their first ground-up Formula 1 engine.",
      "The VW Group (which owns Audi) initially planned to enter F1 with Porsche too.",
      "Porsche's F1 plans were cancelled in 2022 — Audi pressed on alone.",
      "Mattia Binotto, ex-Ferrari Team Principal, joined Audi's F1 project in 2023.",
      "Gabriel Bortoleto is the first Brazilian F1 driver since Felipe Massa.",
      "Bortoleto won the 2024 Formula 2 championship before his F1 debut.",
      "The Hinwil factory sits at 700m altitude — unusual for an F1 operation.",
      "Audi's motorsport budget for F1 is reported to be over €1 billion for the first three years.",
    ],
    cadillac: [
      "Cadillac became the 11th F1 team in 2026 — the first new American entry since Haas.",
      "The entry was initially controversial — FOM rejected their application before being overruled.",
      "They are backed by General Motors — the largest American car company.",
      "Andretti Autosport was the original force behind the entry before GM rebranded it Cadillac.",
      "Michael Andretti spent years fighting the F1 establishment to get this entry approved.",
      "Mario Andretti, Michael's father, won the 1978 F1 World Championship.",
      "The team is based in Silverstone — despite being an American brand.",
      "Cadillac also competes in IndyCar, NASCAR, IMSA, and Formula E.",
      "Their entry was approved by the FIA but initially blocked by the existing teams.",
      "The existing teams opposed the entry partly due to fears of prize money dilution.",
      "Cadillac's F1 car uses a Ferrari power unit while they develop their own engine.",
      "General Motors committed to supplying their own F1-spec engine from 2028.",
      "Kevin Magnussen joined as one of their first drivers for the 2026 season.",
      "Colton Herta was the original intended driver but failed to obtain an FIA Super Licence.",
      "The Cadillac badge last appeared in top-level motorsport at Le Mans.",
      "Their debut at the 2026 Australian GP made them the first new team in 10 years.",
      "The team's short-term goal is simply to score points and learn.",
      "Andretti has won the Indianapolis 500 five times with his team.",
      "General Motors withdrew from F1 in the 1960s — this is their dramatic return.",
      "The Cadillac name is synonymous with American luxury — an unusual F1 identity.",
    ],
    f1: [
      "The first Formula 1 World Championship race was held at Silverstone in 1950.",
      "F1 cars can go from 0 to 200 km/h and back to 0 in under 5 seconds.",
      "A modern F1 car generates enough downforce to drive upside down on a ceiling.",
      "The average F1 driver loses 3–4 kg during a race from sweat alone.",
      "F1 steering wheels can cost up to £50,000 and have over 20 functions.",
      "A single F1 tyre weighs 9.5 kg and can reach temperatures of 120°C.",
      "The Monaco Grand Prix has been held since 1929 — 6 years before F1 existed.",
      "F1 engines rev to 18,000 RPM — nearly three times a road car's limit.",
      "The halo device has saved multiple lives since its introduction in 2018.",
      "DRS (Drag Reduction System) was introduced in 2011 to help overtaking.",
      "An F1 car's brakes can withstand temperatures of 1,000°C.",
      "The fastest recorded pit stop in F1 history is 1.80 seconds by Red Bull in 2023.",
      "F1 cars produce so much downforce they could theoretically fly if driven upside down.",
      "The average G-force through a high-speed corner is 5G — like a fighter jet.",
      "Formula 1 is watched by over 700 million people worldwide each season.",
      "The Monaco circuit has barely changed since 1929 — it would never pass modern safety standards.",
      "F1 brake pedals require over 100kg of force — drivers need strong legs.",
      "The carbon fibre monocoque can withstand 50G impacts in a crash.",
      "Refuelling was banned in F1 after 2009 to reduce race strategy danger.",
      "A full F1 season covers over 50,000 km across 5 continents.",
    ],
  };

  const CONTAINER_ID = 'teamFactsContainer';

  function renderFacts(teamId) {
    const el = document.getElementById(CONTAINER_ID);
    if (!el) return;
    const facts = FACTS[teamId] || FACTS.f1;
    el.innerHTML = facts.map((f, i) =>
      `<div class="tf-item">
        <span class="tf-num">${String(i + 1).padStart(2, '0')}</span>
        <span class="tf-text">${f}</span>
      </div>`
    ).join('');
  }

  /* ── Initial render from saved team ── */
  function getSavedTeamId() {
    try {
      const saved = localStorage.getItem('pitwall_team');
      return saved ? (JSON.parse(saved).id || 'f1') : 'f1';
    } catch { return 'f1'; }
  }

  renderFacts(getSavedTeamId());

  /* ── Re-render whenever a team swatch is clicked (piggyback on storage) ── */
  document.addEventListener('click', e => {
    const swatch = e.target.closest('.team-swatch');
    if (swatch) setTimeout(() => renderFacts(getSavedTeamId()), 50);
  });
})();
